---
title: "Modules de soutien statistique 2025--2026"
format: html
author:
    - name: "Amal Tawfik"
      orcid: "0009-0006-2422-1555"
      ror: "04j47fz63"
      affiliations:
        - name: "HESAV Haute École de Santé - Vaud, HES-SO Haute école spécialisée de Suisse occidentale"
          address: "Av. de Beaumont 21, 1011 Lausanne"
          department: "Ra&D"
      email: "amal.tawfik@hesav.ch"
---

HORAIRE 12:00--13:00\
Salle G/OO/13 \
Ouvert à toutes et tous, sans inscription

# 📅 Planning des modules

| Jour | Date | Module | Présentation |
|------|------|---------|--------------|
| Jeudi | 06.11.2025 | Introduction à R et RStudio : premiers pas, bonnes pratiques et *workflow* | <a href="./01-intro_r_rstudio/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./pdf/01-intro_r_rstudio.pdf" class="btn btn-outline-secondary btn-sm" target="_blank">PDF</a> |
| Jeudi | 15.01.2026 | Nettoyage et manipulation des données avec R : introduction au [tidyverse](https://tidyverse.tidyverse.org/) | <a href="./tidyverse/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./tidyverse/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |
| Jeudi | 12.02.2026 | Analyses bivariées : tableaux croisés, comparaison de moyennes, analyse de variance, corrélation | <a href="./analyses-bivariees/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./analyses-bivariees/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |
| Jeudi | 12.03.2026 | Régression linéaire | <a href="./regression-lineaire/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./regression-lineaire/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |
| Jeudi | 23.04.2026 | Analyses factorielles exploratoires (EFA) et construction d’échelles | <a href="./efa-construction/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./efa-construction/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |
| Jeudi | 21.05.2026 | Visualisation des données avec [ggplot2](https://ggplot2.tidyverse.org/) | <a href="./ggplot2/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./ggplot2/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |
| Jeudi | 18.06.2026 | Régression logistique | <a href="./regression-logistique/index.html" class="btn btn-success btn-sm">Ouvrir</a><a href="./regression-logistique/index.pdf" class="btn btn-outline-secondary btn-sm">PDF</a> |


------------------------------------------------------------------------

> 💡 Astuce PDF : dans chaque présentation, un bouton **« Télécharger le PDF »** ouvre le fichier `index.pdf` correspondant.\
> Pour générer ces PDF localement :
>
> ``` bash
> quarto render <dossier>/index.qmd --to pdf
> ```
>
> (Chrome/Chromium nécessaire pour la conversion revealjs→PDF.)
